// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimesheetGeneratorApp.Data;

#nullable disable

namespace TimesheetGeneratorApp.Migrations.Commit
{
    [DbContext(typeof(CommitContext))]
    partial class CommitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimesheetGeneratorApp.Models.CommitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("author_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("committed_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("jam_akhir")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("jam_mulai")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("jumlah_jam")
                        .HasColumnType("integer");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CommitModel");
                });
#pragma warning restore 612, 618
        }
    }
}
