// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimesheetGeneratorApp.Data;

#nullable disable

namespace TimesheetGeneratorApp.Migrations
{
    [DbContext(typeof(MasterProjectContext))]
    [Migration("20220928030620_AddRelationToCommitModel")]
    partial class AddRelationToCommitModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimesheetGeneratorApp.Models.CommitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MasterProjectModelId")
                        .HasColumnType("integer");

                    b.Property<string>("author_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("committed_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("jam_akhir")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("jam_mulai")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("jumlah_jam")
                        .HasColumnType("integer");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MasterProjectModelId");

                    b.ToTable("CommitModel");
                });

            modelBuilder.Entity("TimesheetGeneratorApp.Models.MasterProjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("accsess_token")
                        .HasColumnType("text");

                    b.Property<string>("host_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string>("project_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.Property<string>("version_control")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MasterProjectModel");
                });

            modelBuilder.Entity("TimesheetGeneratorApp.Models.CommitModel", b =>
                {
                    b.HasOne("TimesheetGeneratorApp.Models.MasterProjectModel", "MasterProjectModel")
                        .WithMany("commits")
                        .HasForeignKey("MasterProjectModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterProjectModel");
                });

            modelBuilder.Entity("TimesheetGeneratorApp.Models.MasterProjectModel", b =>
                {
                    b.Navigation("commits");
                });
#pragma warning restore 612, 618
        }
    }
}
