// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimesheetGeneratorApp.Data;

#nullable disable

namespace TimesheetGeneratorApp.Migrations.HariLibur
{
    [DbContext(typeof(HariLiburContext))]
    [Migration("20220929095757_AddNewTableHariLibur")]
    partial class AddNewTableHariLibur
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimesheetGeneratorApp.Models.HariLiburModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("holiday_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("holiday_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_national_holiday")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("HariLiburModel");
                });
#pragma warning restore 612, 618
        }
    }
}
